version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/backend/data
    env_file:
      - .env
    environment:
      - FRONTEND_URL=http://localhost:5173
    networks:
      - redlife_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - redlife_network

networks:
  redlife_network:
    driver: bridge
